### ISSUE TITLE
Option name "config" appears to be ignored

### ISSUE THREAD

**Issue by verheyenkoen** [schwarzkopfb/tesseract-ocr#3]
In the [docs](https://github.com/schwarzkopfb/tesseract-ocr/blob/master/docs.md) it is mentioned you can pass tesseract CLI configuration options via the `config` option (which can be a string, array of strings or object). That doesn't appear to work. 

From the [code](https://github.com/schwarzkopfb/tesseract-ocr/blob/master/index.js#L128) it seems that the option name should be eiter `c`, `conf`, `confs` or `configs`.

So either the code or the docs are wrong or I'm missing something (probably very obvious) here...

**Comment by schwarzkopfb** [comment]
That was a mistake in the code. I published the patch under v1.1.1 Thank you for pointing that out!
