### ISSUE TITLE
Can't read the image IMPORTANT

### ISSUE THREAD

**Issue by sulaimanO** [schwarzkopfb/tesseract-ocr#4]
Dears,

thank you for your great work

but whill im developing i faced this issue, can you please help me

thanks

this is pic link: http://africaoilgasreport.com/wp-content/uploads/2015/08/qout.jpg

this is my code

> const recognize = require('tesseractocr')
> function t() {
>     recognize(`${__dirname}/OCR/qout.jpg`, (err, text) => {
>         if (err)
>             console.log(err) 
>         else
>             console.log('Yay! Text recognized!', text)
>     })
> }
> t()

and this is the log

`node test.js
{ Error: not found: tesseract
    at getNotFoundError (/Users/sulaiman/Desktop/nodejs ml/node_modules/which/which.js:13:12)
    at F (/Users/sulaiman/Desktop/nodejs ml/node_modules/which/which.js:68:19)
    at E (/Users/sulaiman/Desktop/nodejs ml/node_modules/which/which.js:80:29)
    at /Users/sulaiman/Desktop/nodejs ml/node_modules/which/which.js:89:16
    at /Users/sulaiman/Desktop/nodejs ml/node_modules/isexe/index.js:42:5
    at /Users/sulaiman/Desktop/nodejs ml/node_modules/isexe/mode.js:8:5
    at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT'`

**Comment by schwarzkopfb** [comment]
Hey! It’s because you didn’t installed Tesseract or didn’t add the executable’s location into the PATH on the machine you’re trying to run your code.

Please check out this: https://github.com/schwarzkopfb/tesseract-ocr/blob/master/README.md#installation
and make sure you installed Tesseract properly.
