### ISSUE TITLE
hocr or pdf parameter

### ISSUE THREAD

**Issue by tsippert** [schwarzkopfb/tesseract-ocr#6]
There are two new parameters available in the command line: `pdf` and `hocr`

You can see the documentation here:
- https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#hocr-output
- https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#searchable-pdf-output

Would be nice to have an option to allow the use of this feature.  
For example, there could be a new config option `output` with the `pdf`, `hocr` and `text` (default) options available.

**Comment by originals** [comment]
try
```
    const recognize = tesseract.withOptions({
      language: ['eng'],
      configfiles: ['text', 'hocr']
    });
```

**Comment by schwarzkopfb** [comment]
Hi @tsippert!

As @originals pointed out Tesseract's documentation clarifies that it's just an alias for the corresponding `configfiles` option. However this makes the JS API more expressive, so I implemented the feature you mentioned. It'll land in v2.0 which I'm going to release very soon.

Thank you for the suggestion!
