### ISSUE TITLE
Getting X and Y coordinates of a letter or string.

### ISSUE THREAD

**Issue by blane1988** [schwarzkopfb/tesseract-ocr#7]
Hello. Not really an issue: Since this is a wrapper for Tesseract, is it possible to use hocr to obtain the x and y coordinates of text?

**Comment by originals** [comment]
i was wondering the same =]

check this out:
https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00.html
 at Making Box Files

options lstmbox (each character) or wordstrbox can be used

```
const tesseract = require('tesseractocr');

const recognize = tesseract.withOptions({
      language: ['eng'],
      configfiles: 'makebox'
});

recognize('C:/image.png', (err, text) => {
      if (err) {
        throw err;
      } else {
        console.log(text);
      }
    });
```
gives the output: 
S 51 50 641 134 0
U 51 50 641 134 0
C 51 50 641 134 0
C 51 50 641 134 0
E 51 50 641 134 0
S 51 50 641 134 0
S 51 50 641 134 0

<symbol> <left> <bottom> <right> <top> <page>

**Comment by blane1988** [comment]
That is way cleaner than how I managed to get the coordinates! Very cool, thanks. I will close this issue as well; I think this solution is good.
